# Generated by Django 3.2.7 on 2021-10-06 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usedtrade', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedtrade_post',
            old_name='created_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='usedtrade_post',
            old_name='modified_date',
            new_name='modify_date',
        ),
        migrations.RenameModel(
            old_name='usedtrade_post',
            new_name='Post',
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField()),
                ('modify_date', models.DateField(blank=True, null=True)),
                ('file', models.FileField(upload_to='')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usedtrade.post')),
            ],
        ),
    ]
