# Generated by Django 3.2.7 on 2021-10-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usedtrade', '0002_auto_20211006_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_set', to='usedtrade.post'),
        ),
    ]
