# Generated by Django 3.2.7 on 2021-10-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedtrade', '0003_alter_file_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='usedtrade/post'),
        ),
    ]
