# Generated by Django 3.2.7 on 2021-11-20 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_auto_20211117_2243'),
        ('usedtrade', '0010_auto_20211117_2244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.GenericIPAddressField()),
                ('create_date', models.DateTimeField()),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_author', to=settings.AUTH_USER_MODEL)),
                ('community_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_post', to='community.post')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_receiver', to=settings.AUTH_USER_MODEL)),
                ('used_post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_post', to='usedtrade.post')),
            ],
        ),
    ]
