# Generated by Django 3.2.7 on 2021-11-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_chatroom_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_list', to='common.chatroom'),
        ),
    ]
