# Generated by Django 3.2.9 on 2021-11-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_remove_chat_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='chatroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_list', to='common.chatroom'),
        ),
    ]
