# Generated by Django 3.2.3 on 2021-09-23 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='oneroom_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('create_date', models.DateTimeField()),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('gas_type', models.TextField(blank=True, null=True)),
                ('owner_contact', models.TextField(blank=True, null=True)),
                ('manage_amount', models.FloatField(blank=True, null=True)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('rent_type', models.TextField(blank=True, null=True)),
                ('rent_amount', models.FloatField(blank=True, null=True)),
                ('dedicated_area', models.FloatField(blank=True, null=True)),
                ('common_area', models.FloatField(blank=True, null=True)),
                ('room_num', models.IntegerField(blank=True, null=True)),
                ('toilet_num', models.IntegerField(blank=True, null=True)),
                ('parking', models.BooleanField(blank=True, null=True)),
                ('elevator', models.BooleanField(blank=True, null=True)),
                ('moving_date', models.DateTimeField(blank=True, null=True)),
                ('room_remain', models.IntegerField(blank=True, null=True)),
                ('construction_date', models.DateTimeField(blank=True, null=True)),
                ('floor_total', models.IntegerField(blank=True, null=True)),
                ('floor_num', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '매물 이름',
            },
        ),
    ]
