# Generated by Django 3.2.7 on 2021-10-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0004_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='elevator',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='moving_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='parking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
