# Generated by Django 3.2.7 on 2021-10-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0005_auto_20211008_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='manage_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
