# Generated by Django 3.2.7 on 2021-10-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0007_auto_20211011_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='common_area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='dedicated_area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
