# Generated by Django 3.2.7 on 2021-10-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0009_auto_20211011_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='room_remain',
        ),
        migrations.AddField(
            model_name='post',
            name='room_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='toilet_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
