# Generated by Django 3.2.7 on 2021-10-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0012_auto_20211011_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='modify_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
