# Generated by Django 3.2.7 on 2021-10-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0013_alter_file_modify_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_set', to='oneroom.post'),
        ),
    ]
