# Generated by Django 3.2.7 on 2021-11-24 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0019_post_browse_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oneroom.post'),
        ),
    ]
