# Generated by Django 4.0 on 2022-01-09 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0025_file_rep'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remain', models.IntegerField(blank=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_set', to='oneroom.post')),
            ],
        ),
    ]
