# Generated by Django 4.0 on 2022-01-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0027_post_status_hashtag1_post_status_hashtag2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dedicated_area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
