# Generated by Django 4.0 on 2022-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0029_delete_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_status',
            name='CCTV',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='aircon',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='closet',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='desk',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='doorLock',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='entrance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='fireAlarm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='gasAlarm',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='induction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='refrigerator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='shoeCloset',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='videoPhone',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post_status',
            name='washer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
