# Generated by Django 4.0 on 2022-01-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0030_post_status_cctv_post_status_aircon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='construction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
