# Generated by Django 4.0 on 2022-01-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0031_alter_post_construction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_status',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
