# Generated by Django 3.2.7 on 2021-11-21 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usedtrade', '0010_auto_20211117_2244'),
        ('common', '0005_alter_chat_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='used_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usedtrade_post', to='usedtrade.post'),
        ),
    ]
