# Generated by Django 3.2.9 on 2021-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_remove_chat_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='content2',
            field=models.TextField(null=True),
        ),
    ]
