# Generated by Django 3.2.9 on 2021-11-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20211123_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_status',
            field=models.BooleanField(default=1),
        ),
    ]
