# Generated by Django 3.2.9 on 2021-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_chat_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_status',
            field=models.BooleanField(default=0),
        ),
    ]
