insert into Toch.auth_permission (id, name, content_type_id, codename)
values  (1, 'Can add log entry', 1, 'add_logentry'),
        (2, 'Can change log entry', 1, 'change_logentry'),
        (3, 'Can delete log entry', 1, 'delete_logentry'),
        (4, 'Can view log entry', 1, 'view_logentry'),
        (5, 'Can add permission', 2, 'add_permission'),
        (6, 'Can change permission', 2, 'change_permission'),
        (7, 'Can delete permission', 2, 'delete_permission'),
        (8, 'Can view permission', 2, 'view_permission'),
        (9, 'Can add group', 3, 'add_group'),
        (10, 'Can change group', 3, 'change_group'),
        (11, 'Can delete group', 3, 'delete_group'),
        (12, 'Can view group', 3, 'view_group'),
        (13, 'Can add user', 4, 'add_user'),
        (14, 'Can change user', 4, 'change_user'),
        (15, 'Can delete user', 4, 'delete_user'),
        (16, 'Can view user', 4, 'view_user'),
        (17, 'Can add content type', 5, 'add_contenttype'),
        (18, 'Can change content type', 5, 'change_contenttype'),
        (19, 'Can delete content type', 5, 'delete_contenttype'),
        (20, 'Can view content type', 5, 'view_contenttype'),
        (21, 'Can add session', 6, 'add_session'),
        (22, 'Can change session', 6, 'change_session'),
        (23, 'Can delete session', 6, 'delete_session'),
        (24, 'Can view session', 6, 'view_session'),
        (25, 'Can add oneroom_post', 7, 'add_oneroom_post'),
        (26, 'Can change oneroom_post', 7, 'change_oneroom_post'),
        (27, 'Can delete oneroom_post', 7, 'delete_oneroom_post'),
        (28, 'Can view oneroom_post', 7, 'view_oneroom_post'),
        (29, 'Can add usedtrade_post', 8, 'add_usedtrade_post'),
        (30, 'Can change usedtrade_post', 8, 'change_usedtrade_post'),
        (31, 'Can delete usedtrade_post', 8, 'delete_usedtrade_post'),
        (32, 'Can view usedtrade_post', 8, 'view_usedtrade_post'),
        (33, 'Can add post', 7, 'add_post'),
        (34, 'Can change post', 7, 'change_post'),
        (35, 'Can delete post', 7, 'delete_post'),
        (36, 'Can view post', 7, 'view_post'),
        (37, 'Can add post', 8, 'add_post'),
        (38, 'Can change post', 8, 'change_post'),
        (39, 'Can delete post', 8, 'delete_post'),
        (40, 'Can view post', 8, 'view_post'),
        (41, 'Can add file', 9, 'add_file'),
        (42, 'Can change file', 9, 'change_file'),
        (43, 'Can delete file', 9, 'delete_file'),
        (44, 'Can view file', 9, 'view_file'),
        (45, 'Can add comment', 10, 'add_comment'),
        (46, 'Can change comment', 10, 'change_comment'),
        (47, 'Can delete comment', 10, 'delete_comment'),
        (48, 'Can view comment', 10, 'view_comment'),
        (49, 'Can add nested', 11, 'add_nested'),
        (50, 'Can change nested', 11, 'change_nested'),
        (51, 'Can delete nested', 11, 'delete_nested'),
        (52, 'Can view nested', 11, 'view_nested'),
        (53, 'Can add file', 12, 'add_file'),
        (54, 'Can change file', 12, 'change_file'),
        (55, 'Can delete file', 12, 'delete_file'),
        (56, 'Can view file', 12, 'view_file'),
        (57, 'Can add status', 13, 'add_status'),
        (58, 'Can change status', 13, 'change_status'),
        (59, 'Can delete status', 13, 'delete_status'),
        (60, 'Can view status', 13, 'view_status'),
        (61, 'Can add comment', 14, 'add_comment'),
        (62, 'Can change comment', 14, 'change_comment'),
        (63, 'Can delete comment', 14, 'delete_comment'),
        (64, 'Can view comment', 14, 'view_comment'),
        (65, 'Can add board name', 15, 'add_boardname'),
        (66, 'Can change board name', 15, 'change_boardname'),
        (67, 'Can delete board name', 15, 'delete_boardname'),
        (68, 'Can view board name', 15, 'view_boardname'),
        (69, 'Can add post', 16, 'add_post'),
        (70, 'Can change post', 16, 'change_post'),
        (71, 'Can delete post', 16, 'delete_post'),
        (72, 'Can view post', 16, 'view_post'),
        (73, 'Can add nested', 17, 'add_nested'),
        (74, 'Can change nested', 17, 'change_nested'),
        (75, 'Can delete nested', 17, 'delete_nested'),
        (76, 'Can view nested', 17, 'view_nested'),
        (77, 'Can add attribution', 18, 'add_attribution'),
        (78, 'Can change attribution', 18, 'change_attribution'),
        (79, 'Can delete attribution', 18, 'delete_attribution'),
        (80, 'Can view attribution', 18, 'view_attribution'),
        (81, 'Can add chat', 19, 'add_chat'),
        (82, 'Can change chat', 19, 'change_chat'),
        (83, 'Can delete chat', 19, 'delete_chat'),
        (84, 'Can view chat', 19, 'view_chat'),
        (85, 'Can add chat room', 20, 'add_chatroom'),
        (86, 'Can change chat room', 20, 'change_chatroom'),
        (87, 'Can delete chat room', 20, 'delete_chatroom'),
        (88, 'Can view chat room', 20, 'view_chatroom'),
        (89, 'Can add file', 21, 'add_file'),
        (90, 'Can change file', 21, 'change_file'),
        (91, 'Can delete file', 21, 'delete_file'),
        (92, 'Can view file', 21, 'view_file'),
        (93, 'Can add post_ status', 22, 'add_post_status'),
        (94, 'Can change post_ status', 22, 'change_post_status'),
        (95, 'Can delete post_ status', 22, 'delete_post_status'),
        (96, 'Can view post_ status', 22, 'view_post_status'),
        (97, 'Can add post status', 22, 'add_poststatus'),
        (98, 'Can change post status', 22, 'change_poststatus'),
        (99, 'Can delete post status', 22, 'delete_poststatus'),
        (100, 'Can view post status', 22, 'view_poststatus'),
        (101, 'Can add post like', 23, 'add_postlike'),
        (102, 'Can change post like', 23, 'change_postlike'),
        (103, 'Can delete post like', 23, 'delete_postlike'),
        (104, 'Can view post like', 23, 'view_postlike'),
        (105, 'Can add contact', 24, 'add_contact'),
        (106, 'Can change contact', 24, 'change_contact'),
        (107, 'Can delete contact', 24, 'delete_contact'),
        (108, 'Can view contact', 24, 'view_contact');