insert into Toch.django_content_type (id, app_label, model)
values  (1, 'admin', 'logentry'),
        (3, 'auth', 'group'),
        (2, 'auth', 'permission'),
        (4, 'auth', 'user'),
        (19, 'common', 'chat'),
        (20, 'common', 'chatroom'),
        (15, 'community', 'boardname'),
        (14, 'community', 'comment'),
        (21, 'community', 'file'),
        (17, 'community', 'nested'),
        (16, 'community', 'post'),
        (13, 'community', 'status'),
        (5, 'contenttypes', 'contenttype'),
        (18, 'oneroom', 'attribution'),
        (24, 'oneroom', 'contact'),
        (12, 'oneroom', 'file'),
        (7, 'oneroom', 'post'),
        (23, 'oneroom', 'postlike'),
        (22, 'oneroom', 'poststatus'),
        (6, 'sessions', 'session'),
        (10, 'usedtrade', 'comment'),
        (9, 'usedtrade', 'file'),
        (11, 'usedtrade', 'nested'),
        (8, 'usedtrade', 'post');