# Generated by Django 3.2.7 on 2021-10-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0010_auto_20211011_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='direction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
