# Generated by Django 3.2.7 on 2021-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0014_alter_file_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='oneroom/post'),
        ),
    ]
