# Generated by Django 3.2.7 on 2021-11-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0022_alter_attribution_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='D',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='E',
        ),
    ]
