# Generated by Django 4.0 on 2022-01-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0023_auto_20211124_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_ip',
        ),
        migrations.RemoveField(
            model_name='post',
            name='common_area',
        ),
        migrations.RemoveField(
            model_name='post',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='post',
            name='floor_num',
        ),
        migrations.RemoveField(
            model_name='post',
            name='moving_date',
        ),
        migrations.AddField(
            model_name='post',
            name='year_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
