# Generated by Django 4.0 on 2022-01-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0028_alter_post_dedicated_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attribution',
        ),
    ]
