# Generated by Django 4.0 on 2022-01-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0033_rename_post_status_poststatus_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='liked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
