# Generated by Django 3.2.7 on 2021-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0011_post_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
