# Generated by Django 3.2.7 on 2021-11-20 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0015_alter_file_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(blank=True, null=True)),
                ('A', models.IntegerField(blank=True, null=True)),
                ('B', models.IntegerField(blank=True, null=True)),
                ('C', models.IntegerField(blank=True, null=True)),
                ('D', models.IntegerField(blank=True, null=True)),
                ('E', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
