# Generated by Django 3.2.7 on 2021-11-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0016_attribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='longitude',
            new_name='longtitude',
        ),
    ]
