# Generated by Django 3.2.7 on 2021-11-23 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0017_rename_longitude_post_longtitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
