# Generated by Django 3.2.7 on 2021-11-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oneroom', '0021_alter_attribution_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='post',
            field=models.TextField(),
        ),
    ]
