# Generated by Django 3.2.7 on 2021-10-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedtrade', '0007_auto_20211007_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
