# Generated by Django 3.2.7 on 2021-11-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedtrade', '0010_auto_20211117_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nested',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nested',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
