# Generated by Django 3.2.7 on 2021-11-21 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0003_auto_20211121_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
