# Generated by Django 3.2.7 on 2021-11-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usedtrade', '0011_auto_20211124_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='media/usedtrade/post'),
        ),
    ]
